server:
  port: 8085

spring:
  application:
    name: quant-strategy
  config:
    import: optional:nacos:${spring.application.name}.${spring.cloud.nacos.config.file-extension}
  cloud:
    nacos:
      discovery:
        server-addr: ${NACOS_SERVER:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
      config:
        server-addr: ${NACOS_SERVER:localhost:8848}
        namespace: ${NACOS_NAMESPACE:public}
        file-extension: yml

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
